#!/usr/bin/env python
from i2cdev import I2C

import sys
i2c = I2C(int(sys.argv[1], 16), int(sys.argv[2]))
i2c.write(bytearray(int(sys.argv[3], 16)))
data = i2c.read(int(sys.argv[4]))
i2c.close()
print data
